---
title: "Exercise1_1"
author: "Giulio Vicentini"
date: "4/5/2020"
output: html_document
---

Create  vectors and dataframe
```{r}
name <- c('Loch Ness', 'Loch Lommond', 'Loch Morar', 'Loch Tay', 'Loch Awe', 'Loch Maree', 'Loch Ericht', 'Loch Lochy', 'Loch Rannoch', 'Loch Shiel', 'Loch Katrine', 'Loch Arkaig', 'Loch Shin')

volume <- c(7.45, 2.6, 2.3, 1.6, 1.2, 1.09, 1.08, 1.07, 0.97, 0.79, 0.77, 0.75, 0.35)
 
area <- c(56, 71, 27, 26.4, 39, 28.6, 18.6, 16, 19, 19.5, 12.4, 16, 22.5)

length <- c(39, 36, 18.8, 23, 41, 20, 23, 16, 15.7, 28, 12.9, 19.3, 27.8)

max_depth <- c(230, 190, 310, 150, 94, 114, 156, 162, 134, 128, 151, 109, 49)

mean_depth <- c(132, 37, 87, 60.6, 32, 38, 57.6, 70, 51, 40, 43.4, 46.5, 15.5)

scottish.lakes <- data.frame(name, volume, area, length, max_depth, mean_depth, stringsAsFactors = FALSE)
```

evaluate the highest and lowest volume and area lake
```{r}
max(scottish.lakes$volume)
min(scottish.lakes$volume)
max(scottish.lakes$area)
min(scottish.lakes$area)
```

order the frame with respect to the area and determine the two largest area lakes
```{r}
scottish.lakes<-scottish.lakes[order(area, decreasing=TRUE),]
scottish.lakes$area[1]
scottish.lakes$area[2]
```

sum up the areas
```{r}
sum(scottish.lakes$area)
```



